server.port=8080
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=never
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
server.tomcat.accesslog.directory=/proc/self/fd
server.tomcat.accesslog.prefix=1
server.tomcat.accesslog.suffix=
server.tomcat.accesslog.file-date-format=
server.tomcat.accesslog.buffered=false
